config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :posts
  validates_presence_of :name
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  validates_presence_of :title, :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout "basic_layout"

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    if !post_create_params['author_id'].to_s.empty?
      author_id = post_create_params['author_id']
    else
      author = Author.new(:name => post_create_params['author_name'])
      author.save
      author_id = author.id
    end

    @post = Post.new.tap do |p|
      p.title     = post_create_params['title']
      p.body      = post_create_params['body']
      p.author_id = author_id
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post,
                    :notice => 'Post was successfully created.') }
        format.json { render :json => @post,
                    :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors,
                      :status => :unprocessable_entity }
      end
    end

  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_update_params)
        format.html { redirect_to(@post,
                    :notice => 'Post was successfully updated.') }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors,
                      :status => :unprocessable_entity }
      end
    end

  end

  def destroy
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.destroy
        format.html { redirect_to(posts_path,
                    :notice => 'Post was successfully destroyed.') }
        format.json { head :no_content }
      else
        format.json { render :json => @post.errors,
                      :status => :unprocessable_entity }
      end
    end

  end

  private

  def post_create_params
    params.require(:post).permit(:title, :body, :author_id, :author_name)
  end

  def post_update_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/basic_layout.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div class="padding-left">
<%= yield %>

app/views/posts/edit.html.erb
<div class="container bg-info">
  <div align="center">
    <h1>Edit post</h1>

    <%= form_with(model: @post, local: true) do |form| %>

      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:
          </h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
      </p>

      <p>
        <%= form.submit %>
      </p>

    <% end %>

    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">

  <div id="root"></div>

  <h1>Blog Posts</h1>

  <p id="notice"><%= notice %></p>

  <table class="table table-striped table-hover table-bordered">
    <tr align="left">
      <th class="bg-primary">Title</th>
      <th class="bg-success">Author</th>
      <th class="bg-warning">Created/Updated</th>
      <th class="bg-danger">Actions</th>
      <th class="bg-danger"></th>
      <th class="bg-danger"></th>
    </tr>
    <% @posts.each do |post| %>
      <tr>
        <td><strong><%= post.title %></strong></td>
        <td><%= post.author.name %></td>
        <td>
          <small><%= post.updated_at.strftime("%l:%M%p %m/%d/%Y") %></small>
        </td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post_path(post),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <div style="padding-top: 20px"><%= link_to 'New Post', new_post_path %></div>
</div>

app/views/posts/new.html.erb
<div class="container bg-info">
  <div align="center">
    <h1>New Post</h1>

    <%= form_with scope: :post, url: posts_path, local: true do |form| %>

      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:
          </h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
      </p>

      <p>
        <%= form.label :existing_author %><br>
        <%= form.collection_select :author_id, Author.order(:name), :id, :name, include_blank: true %>
      </p>

      <p>
        <%= form.label :new_author %><br>
        <%= form.text_field :author_name, id: :author_name %>
      </p>

      <p><%= form.submit %></p>
    <% end %>

    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<div align="center">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <div class="bg-warning">
      <h3 class="bg-info"><%= @post.title %></h3>
      <div><%= @post.body %></div>
    </div>
  </div>

  <%= link_to 'Back', posts_path %>
</div>